# Standards: 0.11
---

# 1.6.1.5 Ensure the MCS Translation Service (mcstrans) is not installed (Scored)

- name: 1.6.1.5 Ensure the MCS Translation Service (mcstrans) is not installed (Scored)
  yum:
    name: mcstrans
    state: removed
  tags:
      - level-2
      - section-1
      - "1.1.11"
      - scored
