# Standards: 0.11
---

# 4.1.1.3 Ensure audit logs are not automatically deleted (Scored)

- name: 4.1.1.3 Ensure audit logs are not automatically deleted
  lineinfile:
    dest: "{{ cis_audit_auditd_filename }}"
    line: "max_log_file_action = keep_logs"
  tags:
    - "4.1.1.3"
    - level-2
    - section-4
    - scored