# Standards: 0.11
---

# 4.1.3 Ensure auditing for processes that start prior to auditd is enabled

- name: 4.1.3 Update grub with audit enabled
  shell: "sed -i 's/rd.shell=0/rd.shell=0 audit=1/g' /etc/default/grub"
  tags:
    - "4.1.3"
    - level-2
    - section-4
    - scored

- name: 4.1.3 Update grub
  shell: "grub2-mkconfig -o /boot/grub2/grub.cfg"
  tags:
    - "4.1.3"
    - level-2
    - section-4
    - scored