# Standards: 0.11
---

# 2.2.21 Ensure talk Server is not enabled

- name: 2.2.21 - Ensure Talk Server is not enabled
  service:
    name: "ntalk"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - "2.2.21"
    - scored
