# Standards: 0.11
---

# 2.2.18 Ensure telnet Server is not enabled

- name: 2.2.18 - Ensure telnet Server is not enabled
  service:
    name: "telnet"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - "2.2.18"
    - scored
