# Standards: 0.11
---

# 2.2.20 Ensure Rsync Server is not enabled

- name: 2.2.20 - Ensure Rsync Server is not enabled
  service:
    name: "rsyncd"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - "2.2.20"
    - scored
