# Standards: 0.11
---

# 2.2.19 Ensure tftp Server is not enabled

- name: 2.2.19 - Ensure tftp Server is not enabled
  service:
    name: "tftp"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - "2.2.19"
    - scored
