# Standards: 0.11
---

# 2.2.17 Ensure rsh Server is not enabled

- name: 2.2.17.1 - Ensure rsh Server is not enabled
  service:
    name: "rsh"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - "2.2.17"
    - scored

- name: 2.2.17.2 - Ensure rlogin Server is not enabled
  service:
    name: "rlogin"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - "2.2.17"
    - scored

- name: 2.2.17.3 - Ensure rexec Server is not enabled
  service:
    name: "rexec"
    enabled: false
    state: stopped
  ignore_errors: true
  tags:
    - level-1
    - "2.2.17"
    - scored
