# Standards: 0.11
---

# 3.5.2.1 Ensure IPv6 default deny firewall policy

- name: 3.5.2.1 Ensure IPv6 default deny firewall policy
  shell: "ip6tables -P INPUT DROP && ip6tables -P OUTPUT DROP && ip6tables -P FORWARD DROP"
  tags:
    - level-1
    - section-1
    - "3.5.2.1"
    - scored
