# Standards: 0.11
---

# 3.5.2.2 Ensure IPv6 loopback traffic is configured

- name: 3.5.2.2 - Ensure IPv6 loopback traffic is configured
  shell: "ip6tables -A INPUT -i lo -j ACCEPT && ip6tables -A OUTPUT -o lo -j ACCEPT && ip6tables -A INPUT -s ::1 -j DROP"
  tags:
    - level-1
    - section-1
    - "3.5.2.2"
    - scored
