---

# 5.2.14 - Ensure SSH Idle Timeout Interval is configured

- name: 5.2.14 - Ensure SSH Client Alive Interval is configured
  lineinfile:
    regexp: "^ClientAliveInterval\\s+"
    line: "ClientAliveInterval {{ cis_sshd_client_alive_interval }}"
    dest: "/etc/ssh/sshd_config"
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.14"
    - scored

- name: 5.2.14 - Ensure SSH Client Alive Count Max is configured
  lineinfile:
    regexp: "^ClientAliveCountMax\\s+"
    line: "ClientAliveCountMax {{ cis_sshd_client_alive_count_max }}"
    dest: "/etc/ssh/sshd_config"
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.14"
    - scored